#!/data/data/com.termux/files/usr/bin/env fish

function style --argument-names color text
    gum style --foreground=$color $text
end

function error --argument-names name comment
    set name (string escape --style script -- $name)

    echo -n "- $(style '#5de45e' $name)"
    test -n "$comment" && echo -n " ($(style '#ff69f0' $comment))"
    echo
end

set contacts (termux-contact-list |
    yq --no-colors ".[]")

echo "Validations for $(style '#c9528f' phone):"

for item in $contacts
    set name (echo $item | yq ".name")
    set number (echo $item | yq ".number")

    string match --quiet --regex '\s' -- $number &&
        error $name "contains spaces"
    string match --quiet --regex '^\+7' -- $number &&
        error $name "starts with +7"
end

echo
echo "Validations for $(style '#c9528f' name):"

for item in $contacts
    set name (echo $item | yq ".name")

    string match --quiet --regex '\w+ \(\w[A-z ]+, \w[A-z ]+, \w[A-z ]+\)' -- $number ||
        error $name "doesn't match the pattern"
end

read --prompt-str="Press any key to continue..." --nchars=1
