#!/data/data/com.termux/files/usr/bin/env fish

function style --argument-names color text
    gum style --foreground=$color $text
end

function error --argument-names name message
    set name (string escape --style script -- $name)

    echo "- Contact $(style '#5de45e' $name) $message"
end

set contacts (termux-contact-list |
    yq --no-colors ".[]")

for item in $contacts
    set name (echo $item | yq ".name")
    set number (echo $item | yq ".number")

    string match --quiet --regex '\s' -- $number &&
        error $name "contains spaces inside a number"
    string match --quiet --regex '\w+ \(\w[A-z ]+, \w[A-z ]+, \w[A-z ]+\)' -- $number ||
        error $name "doesn't match the $(style '#e5bf5a' '{{person_name}} ({{work_place_category}}, {{city}}, {{work_place}})') pattern"
end

read --prompt-str="Press any key to continue..." --nchars=1
