#!/data/data/com.termux/files/usr/bin/env fish

source /data/data/com.termux/files/home/.shortcuts/utils/inputs.fish
source /data/data/com.termux/files/home/.shortcuts/utils/constants.fish

set category_info "$(spinner "🏹 Choose the category" gui tui cli library)"
test "$(get $category_info code)" != $success && exit
set category (get $category_info text)

set language_info "$(spinner "💻 Choose the language" fish go javascript tinyscheme json yaml markdown)"
test "$(get $language_info code)" != $success && exit
set language (get $language_info text)

set name_info (text "🏷️ Choose the project name")
test "$(get $name_info code)" != $success && exit
set name (get $name_info text)

set visibility_info "$(spinner "👁️ Choose the visibility" public private)"
test "$(get $visibility_info code)" != $success && exit
set visibility (get $visibility_info text)

gh repo create "$language-$type-$name" --$visibility --license mit
