#!/data/data/com.termux/files/usr/bin/env fish

source /data/data/com.termux/files/home/.shortcuts/utils/inputs.fish
source /data/data/com.termux/files/home/.shortcuts/utils/constants.fish

set brightness_info "$(spinner "🌞 Choose the brightness" minimal normal highest)"
test "$(get $brightness_info code)" != $success && exit
set brightness (get $brightness_info text)

set brightness_integer 10

switch $brightness
    case normal
        set brightness_integer 50
    case highest
        set brightness_integer 100
end

termux-brightness $brightness_integer
